[env:teensy41_app]
platform = teensy
board = teensy41
framework = arduino

lib_deps =
    https://github.com/ssaenger/FlasherX-Ethernet_Support.git
    khoih-prog/AsyncWebServer_Teensy41@^1.7.0
    khoih-prog/Teensy41_AsyncTCP@^1.1.0

; build_src_filter removed so all `src/` files are compiled (networking, hardware, etc.)
